<?php

/**
 * @file
 * Contains the redirect_from_identifier.module.
 */

/**
 * Implements hook_theme().
 */
function redirect_from_identifier_theme($existing, $type, $theme, $path) {
  return [
    'redirect_from_identifier' => [
      'variables' => ['ids' => null],
    ],
  ];
}

/**
 * Default preprocessor function for the redirect_from_identifier hook.
 */
function template_preprocess_redirect_from_identifier(&$variables) {
  $variables['attributes'] = [
    'id' => ['redirect_from_identifier'],
  ];
  if ($variables['ids']) {
    // Get all entities with the id (entity types are an admin option).
    // Load each entity, and retun a list (one item per entity) with the
    // title and a link to it.
  }
}
