<?php

/**
 * @file
 * Contains the redirect_from_identifier.module.
 */

/**
 * Implements hook_theme().
 */
function redirect_from_identifier_theme($existing, $type, $theme, $path) {
  return [
    'redirect_from_identifier' => [
      'variables' => ['ids' => null],
    ],
  ];
}

/**
 * Default preprocessor function for the redirect_from_identifier hook.
 */
function template_preprocess_redirect_from_identifier(&$variables) {
  $variables['attributes'] = [
    'id' => ['redirect_from_identifier'],
  ];
  if ($variables['ids']) {
    $config = \Drupal::config('redirect_from_identifier.settings');
    $variables['message'] = $config->get('redirect_from_identifier_multiple_node_message');

    // Get each node, and its label and URL.
    $variables['nodes'] = [];
    foreach ($variables['ids'] as $id) {
      $entity = \Drupal::entityTypeManager()->getStorage('node')->load($id);
      $node_data = [];
      $node_data['label'] = $entity->label();
      $node_data['url'] = $entity->toUrl()->toString();
      $variables['nodes'][] = $node_data;
    }
  }
}
